# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.11.1

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t yannchav/node-js-sample:${CIRCLE_SHA1} .

      - run:
          name: Run Docker Image
          command: |
            docker run -p 8080:8080 yannchav/node-js-sample:${CIRCLE_SHA1}

      - run:
          name: Test home response
          command: |
            RESPONSE=$(curl -s http://localhost:8080)
            if echo "$RESPONSE" | grep -q "<h1>BackSpace Academy</h1>"; then
              echo "Verification passed: Home contains title 'Backspace Academy'."
            else
              echo "Verification failed: Home does not contain 'Backspace Academy'."
              exit 1
            fi
      - run:
          name: Test /users response
          command: |
            RESPONSE=$(curl -s http://localhost:8080/users)
            if echo "$RESPONSE" | grep -q "respond with a resource"; then
              echo "Verification passed: The response contains 'respond with a resource'."
            else
              echo "Verification failed: The response does not contain 'respond with a resource'."
              exit 1
            fi

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-test-and-push: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
